{
  "uid" : "56db04254d6dff00",
  "name" : "Update created user",
  "fullName" : "tests.test_users.TestUsers#test_update_user",
  "historyId" : "27203c15b0353887295772397967e8ef",
  "time" : {
    "start" : 1742205687439,
    "stop" : 1742205687439,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}",
  "statusTrace" : "self = <test_users.TestUsers object at 0x7fdb261061d0>\n\n    @pytest.fixture(autouse=True)\n    def cleanup_users(self):\n        \"\"\"Очищаем список юзеров перед каждым тестом\"\"\"\n>       self.api_users.delete_all_users()\n\ntests/test_users.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices/users/api_users.py:96: in delete_all_users\n    feature = self.get_all_users()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.users.api_users.UsersAPI object at 0x7fdb258c55a0>\n\n    @allure.step(\"Get all users\")\n    def get_all_users(self):\n        response = requests.get(\n            url=self.endpoints.get_users,\n            headers=self.headers.basic,\n            params={\"limit\": 20},\n        )\n>       assert response.status_code == 200, response.json()\nE       AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n\nservices/users/api_users.py:49: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1742205682193,
      "stop" : 1742205682195,
      "duration" : 2
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "cleanup_users",
    "time" : {
      "start" : 1742205687439,
      "stop" : 1742205688412,
      "duration" : 973
    },
    "status" : "failed",
    "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/API_Auto/API_Auto/tests/test_users.py\", line 13, in cleanup_users\n    self.api_users.delete_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 96, in delete_all_users\n    feature = self.get_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
    "steps" : [ {
      "name" : "Delete all users",
      "time" : {
        "start" : 1742205687439,
        "stop" : 1742205688412,
        "duration" : 973
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 96, in delete_all_users\n    feature = self.get_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
      "steps" : [ {
        "name" : "Get all users",
        "time" : {
          "start" : 1742205687440,
          "stop" : 1742205688411,
          "duration" : 971
        },
        "status" : "failed",
        "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
        "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : true,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 1,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "_xunit_setup_method_fixture_TestUsers",
    "time" : {
      "start" : 1742205687439,
      "stop" : 1742205687439,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "_xunit_setup_method_fixture_TestUsers::0",
    "time" : {
      "start" : 1742205688434,
      "stop" : 1742205688434,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Users"
  }, {
    "name" : "epic",
    "value" : "Administration"
  }, {
    "name" : "tag",
    "value" : "regress"
  }, {
    "name" : "tag",
    "value" : "critical_path"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_users"
  }, {
    "name" : "subSuite",
    "value" : "TestUsers"
  }, {
    "name" : "host",
    "value" : "fv-az1280-703"
  }, {
    "name" : "thread",
    "value" : "2565-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_users"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 4,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "fae4f7f60a574f9f",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/26/#testresult/fae4f7f60a574f9f",
        "status" : "failed",
        "statusDetails" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}",
        "time" : {
          "start" : 1742205452367,
          "stop" : 1742205452367,
          "duration" : 0
        }
      }, {
        "uid" : "cb776fb0ffbb59bd",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/24/#testresult/cb776fb0ffbb59bd",
        "status" : "passed",
        "time" : {
          "start" : 1741967975011,
          "stop" : 1741967978513,
          "duration" : 3502
        }
      }, {
        "uid" : "31f596cee83f90ee",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/23/#testresult/31f596cee83f90ee",
        "status" : "passed",
        "time" : {
          "start" : 1741966135276,
          "stop" : 1741966138501,
          "duration" : 3225
        }
      }, {
        "uid" : "6187b474e9145da8",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/22/#testresult/6187b474e9145da8",
        "status" : "passed",
        "time" : {
          "start" : 1741964642354,
          "stop" : 1741964646069,
          "duration" : 3715
        }
      }, {
        "uid" : "848eaae6fea23ab5",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/21/#testresult/848eaae6fea23ab5",
        "status" : "passed",
        "time" : {
          "start" : 1741964086438,
          "stop" : 1741964090152,
          "duration" : 3714
        }
      } ]
    },
    "tags" : [ "regress", "critical_path" ]
  },
  "source" : "56db04254d6dff00.json",
  "parameterValues" : [ ]
}